server.port=0

spring.application.name=ProductsMicroservice
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
#spring.kafka.producer.properties.retry.backoff.ms=1000

spring.kafka.producer.properties.delivery.timeout.ms=120000

spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# Topic created on startup. Tests and the CI smoke test run a single broker,
# so they set replicas and min.insync.replicas to 1.
app.kafka.topic.partitions=3
app.kafka.topic.replicas=3
app.kafka.topic.min-insync-replicas=2
